### ISSUE TITLE
Support Hashgrid/InstantNGP NeRF backbone?

### ISSUE THREAD

**Issue by kxhit** [NagabhushanSN95/ViP-NeRF#1]
Hi, thanks for open-sourcing such great work!

I noticed the NeRF backbone is based on vanilla NeRF and I'm wondering if it can be replaced by InstantNGP easily to obtain a much faster converge speed. Is there any plan to support the InstantNGP backbone or any insights to do it? Thanks!

**Comment by NagabhushanSN95** [comment]
Hi, thank you for your interest in our work. Since the major component of our model is just an additional loss function (and a small tweak to the network), it should be easily portable to instant-ngp. Simply modify the tiny MLP used by instant-ngp to output an additional view-dependent visibility and add the two losses - L_v and L_{vip}. It should work. Please let me know if you run into any issues or if you have any follow-up questions.

Yes, we do have a plan to extend this to TensoRF and instant-ngp, but it may take a couple of months, Not yet confirmed, though.

**Comment by kxhit** [comment]
Great! Thanks for the quick reply. Will let you know if I have some results.
